[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
nom = "7.1.3"
pest = "2.7.15"
pest_derive = "2.7.15"
regex = "1.11.1"
